[[appdxbitcoinimpproposals]]
[appendix]
== Mapendekezo ya Uboreshaji wa Bitcoin

Mapendekezo ya Uboreshaji wa Bitcoin ni hati za muundo zinazotoa habari kwa jamii ya Bitcoin au zinaelezea kipengele kipya cha Bitcoin au michakato yake au mazingira yake.

Kulingana na BIP1 _Madhumuni ya BIP na Mwongozo_, kuna aina tatu((("BIPs (Bitcoin Improvement Proposals)", "types of"))) za BIP:

_BIP ya Kawaida_:: Inaelezea mabadiliko yoyote yanayoathiri utekelezaji mwingi au wote wa Bitcoin, kama vile mabadiliko kwenye itifaki ya mtandao, mabadiliko katika sheria za uhalali wa vitalu au miamala, au mabadiliko au nyongeza yoyote inayoathiri uingiliano wa programu zinazotumia Bitcoin.
_BIP ya Habari_:: Inaelezea tatizo la muundo wa Bitcoin au inatoa mwongozo wa jumla au habari kwa jamii ya Bitcoin, lakini haipendekezei kipengele kipya. BIP za habari hazijawaakilishi lazima makubaliano ya jamii ya Bitcoin au mapendekezo, kwa hivyo watumiaji na watekelezaji wanaweza kupuuza BIP za habari au kufuata ushauri wake.
_BIP ya Mchakato_:: Inaelezea mchakato wa Bitcoin au inapendekeza mabadiliko kwa (au tukio katika) mchakato. BIP za mchakato ni kama BIP za kawaida lakini zinatumika kwa maeneo mengine ya itifaki ya Bitcoin yenyewe. Zinaweza kupendekeza utekelezaji lakini si kwenye msingi wa msimbo wa Bitcoin; mara nyingi zinahitaji makubaliano ya jamii. Tofauti na BIP za habari, ni zaidi ya mapendekezo, na watumiaji kwa kawaida hawana uhuru wa kuzipuuza. Mifano inajumuisha taratibu, mwongozo, mabadiliko ya mchakato wa kufanya maamuzi, na mabadiliko ya zana au mazingira yanayotumiwa katika maendeleo ya Bitcoin. BIP yoyote ya meta pia inachukuliwa kuwa BIP ya mchakato.

BIP zinaandikwa katika https://oreil.ly/jjO0R[hifadhi yenye matoleo kwenye GitHub].
Hati iliyopewa leseni ya MIT kutoka mradi wa chanzo wazi wa Bitcoin Core,
iliyorudiwa hapa katika hali iliyohaririwa, inaelezea BIP zipi inazotekeleza, ikiwa ni pamoja na orodha
ya Ombi la Kuvuta (PR) na toleo la Bitcoin Core ambapo usaidizi kwa kila BIP uliongezwa au
ulibadilika kwa kiasi kikubwa.

BIP ambazo ((("BIPs (Bitcoin Improvement Proposals)", "implemented by Bitcoin Core", id="bips-implement")))((("Bitcoin Core", "BIPs implemented by", id="bitcoin-core-bips")))zinatekelezwa na Bitcoin Core:

-    BIP9: Mabadiliko yanayoruhusu uma laini nyingi kupelekwa kwa wakati mmoja yametekelezwa tangu v0.12.1 (PR #7575).
-    BIP11: Matokeo ya multisig ni ya kawaida tangu v0.6.0 (PR #669).
-    BIP13: Umbizo la anwani kwa anwani za P2SH limetekelezwa tangu v0.6.0 (PR #669).
-    BIP14: Mfuatano mdogo wa toleo unatumika kama Wakala wa Mtumiaji tangu v0.6.0 (PR #669).
-    BIP16: Sheria za tathmini ya pay-to-script-hash zimetekelezwa tangu v0.6.0, na zilianza kutumika Aprili 1 2012 (PR #748).
-    BIP21: Umbizo la URI kwa malipo ya Bitcoin limetekelezwa tangu v0.6.0 (PR #176).
-    BIP22: Itifaki ya RPC ya 'getblocktemplate' (GBT) kwa uchimbaji imetekelezwa tangu v0.7.0 (PR #936).
-    BIP23: Baadhi ya nyongeza za GBT zimetekelezwa tangu v0.10.0rc1, ikiwa ni pamoja na longpolling na mapendekezo ya vitalu (PR #1816).
-    BIP30: Sheria za tathmini za kukataza uundaji wa miamala mipya yenye txid sawa na miamala ya awali ambayo haijatumiwa kabisa zimetekelezwa tangu v0.6.0, na sheria ilianza kutumika Machi 15 2012 (PR #915).
-    BIP31: Ujumbe wa itifaki wa 'pong' (na toleo la itifaki limeinuliwa hadi 60001) limetekelezwa tangu v0.6.1 (PR #1081).
-    BIP32: Pochi za Kudeterminisitiki za Kidaraja zimetekelezwa tangu v0.13.0 (PR #8035).
-    BIP34: Sheria inayohitaji vitalu kuwa na urefu wao (nambari) katika ingizo la coinbase, na utangulizi wa vitalu vya toleo la 2 imetekelezwa tangu v0.7.0. Sheria ilianza kutumika kwa vitalu vya toleo la 2 kuanzia kitalu 224413 (Machi 5, 2013), na vitalu vya toleo la 1 haviruhusiwi tena tangu kitalu 227931 (Machi 25, 2013) (PR #1526).
-    BIP35: Ujumbe wa itifaki wa 'mempool' (na toleo la itifaki limeinuliwa hadi 60002) umetekelezwa tangu v0.7.0 (PR #1641). Kuanzia v0.13.0, hii inapatikana tu kwa marika ya +NODE_BLOOM+ (BIP111).

[role="less_space pagebreak-before"]
-    BIP37: Uchujaji wa bloom kwa usambazaji wa muamala, miti ya Merkle ya sehemu kwa vitalu, na toleo la itifaki limeinuliwa hadi 70001 (kuwezesha wateja wepesi wa bandwidth ndogo) vimetekelezwa tangu v0.8.0 (PR #1795). Imezimwa kwa chaguo-msingi tangu v0.19.0, inaweza kuwezeshwa na chaguo la +-peerbloomfilters+.
-    BIP42: Hitilafu iliyosababisha ratiba ya ruzuku kuanza upya baada ya kitalu 13440000 ilitengenezwa katika v0.9.2 (PR #3842).
-    BIP43: Pochi za maelezo za majaribio zilizoanzishwa katika v0.21.0 kwa chaguo-msingi hutumia upatikanaji wa Pochi ya Kudeterminisitiki ya Kidaraja uliopendekezwa na BIP43 (PR #16528).
-    BIP44: Pochi za maelezo za majaribio zilizoanzishwa katika v0.21.0 kwa chaguo-msingi hutumia upatikanaji uliopendekezwa na BIP44 (PR #16528).
-    BIP49: Pochi za maelezo za majaribio zilizoanzishwa katika v0.21.0 kwa chaguo-msingi hutumia upatikanaji uliopendekezwa na BIP49 (PR #16528).
-    BIP61: Ujumbe wa itifaki wa 'reject' (na toleo la itifaki limeinuliwa hadi 70002) uliongezwa katika v0.9.0 (PR #3185). Kuanzia v0.17.0, kama kutuma ujumbe wa kukataa kunaweza kusanidiwa kwa chaguo la ++-enablebip61++, na usaidizi umepunguzwa (umezimwa kwa chaguo-msingi) kuanzia v0.18.0. Usaidizi uliondolewa katika v0.20.0 (PR #15437).
-    BIP65: Uma laini wa ++CHECKLOCKTIMEVERIFY++ ulichanganywa katika v0.12.0 (PR #6351), na kurudishwa nyuma kwa v0.11.2 na v0.10.4. +CLTV+ ya mempool peke yake iliongezwa katika PR #6124.
-    BIP66: Sheria kali za DER na vitalu vya toleo 3 vinavyohusiana vimetekelezwa tangu v0.10.0 (PR #5713).
-    BIP68: Vizuizi vya mfuatano vimetekelezwa kuanzia v0.12.1 (PR #7184), na vimezikwa tangu v0.19.0 (PR #16060).
-    BIP70 71 72: Usaidizi wa Itifaki ya Malipo umepatikana kwenye GUI ya Bitcoin Core tangu v0.9.0 (PR #5216). Usaidizi unaweza kuzimwa kwa hiari wakati wa ujenzi tangu v0.18.0 (PR 14451), na umezimwa kwa chaguo-msingi wakati wa ujenzi tangu v0.19.0 (PR #15584). Uliondolewa kuanzia v0.20.0 (PR 17165).
-    BIP84: Pochi za maelezo za majaribio zilizoanzishwa katika v0.21.0 kwa chaguo-msingi hutumia upatikanaji uliopendekezwa na BIP84. (PR #16528)
-    BIP86: Pochi za maelezo kwa chaguo-msingi hutumia upatikanaji wa Pochi ya Kudeterminisitiki ya Kidaraja uliopendekezwa na BIP86 tangu v23.0 (PR #22364).
-    BIP90: Utaratibu wa kusababisha uanzishaji wa BIP 34, 65, na 66 umerahisishwa hadi ukaguzi wa urefu wa kitalu tangu v0.14.0 (PR #8391).
-    BIP111: biti ya huduma ya +NODE_BLOOM+ iliongezwa na kulazimishwa kwa matoleo yote ya marika kuanzia v0.13.0 (PR #6579 na PR #6641).
-    BIP112: Opcode ya +CHECKSEQUENCEVERIFY+ imetekelezwa tangu v0.12.1 (PR #7524), na imezikwa tangu v0.19.0 (PR #16060).
-    BIP113: Hesabu za kufuli cha wakati wa wastani wa muda wa kati zimetekelezwa tangu v0.12.1 (PR #6566), na zimezikwa tangu v0.19.0 (PR #16060).
-    BIP125: Uashiria wa kubadilisha-kwa-ada wa hiari umetekelezwa kwa sehemu.
-    BIP130: Tangazo la vichwa vya habari moja kwa moja linashughulikiwa na matoleo ya marika ≥70012 kuanzia v0.12.0 (PR 6494).
-    BIP133: Ujumbe wa feefilter unashughulikiwa na kutumwa kwa matoleo ya marika ≥70013 kuanzia v0.13.0 (PR 7542).
-    BIP141: Shahidi Iliyotenganishwa (Safu ya Makubaliano) kuanzia v0.13.0 (PR 8149), iliyobainishwa kwa mainnet kuanzia v0.13.1 (PR 8937), na imezikwa tangu v0.19.0 (PR #16060).
-    BIP143: Uthibitishaji wa Saini ya Muamala kwa Programu ya Shahidi ya Toleo 0 kuanzia v0.13.0 (PR 8149), iliyobainishwa kwa mainnet kuanzia v0.13.1 (PR 8937), na imezikwa tangu v0.19.0 (PR #16060).
-    BIP144: Shahidi Iliyotenganishwa kuanzia 0.13.0 (PR 8149).
-    BIP145: Masasisho ya getblocktemplate kwa Shahidi Iliyotenganishwa kuanzia v0.13.0 (PR 8149).
-    BIP147: Uma laini wa +NULLDUMMY+ kuanzia v0.13.1 (PR 8636 na PR 8937), umezikwa tangu v0.19.0 (PR #16060).
-    BIP152: Uhamisho wa vitalu vifupi na maboresho yanayohusiana yanatumika kuanzia v0.13.0 (PR 8068).
-    BIP155: Ujumbe wa 'addrv2' na 'sendaddrv2' unaowezesha usambazaji wa anwani za Tor V3 (na mitandao mingine) unasaidiwa kuanzia v0.21.0 (PR 19954).
-    BIP157 158: Vichujio vya Vitalu Vifupi kwa Wateja Wepesi vinaweza kuorodhesha faharasa kuanzia v0.19.0 (PR #14121) na kutoa huduma kwa marika kwenye mtandao wa P2P kuanzia v0.21.0 (PR #16442).
-    BIP159: Biti ya huduma ya +NODE_NETWORK_LIMITED+ inaashiria kuanzia v0.16.0 (PR 11740), na nodi kama hizo zimeunganishwa kuanzia v0.17.0 (PR 10387).
-    BIP173: Anwani za Bech32 kwa matokeo ya asili ya Shahidi Iliyotenganishwa zinasaidiwa kuanzia v0.16.0 (PR 11167). Anwani za Bech32 huzalishwa kwa chaguo-msingi kuanzia v0.20.0 (PR 16884).
-    BIP174: RPC za kuendeshea Miamala ya Bitcoin Iliyosainiwa Kwa Sehemu (PSBT) zinapatikana kuanzia v0.17.0 (PR 13557).
-    BIP176: Kizidishi cha Bits [QT peke yake] kinasaidiwa kuanzia v0.16.0 (PR 12035).
-    BIP325: Mtandao wa majaribio wa Signet unasaidiwa kuanzia v0.21.0 (PR 18267).
-    BIP339: Usambazaji wa miamala kwa wtxid unasaidiwa kuanzia v0.21.0 (PR 18044).
-    BIP340 341 342: Sheria za uthibitishaji wa Taproot (ikiwa ni pamoja na saini za schnorr na majani ya Tapscript) zimetekelezwa kuanzia v0.21.0 (PR 19953), na uanzishaji wa mainnet kuanzia v0.21.1 (PR 21377, PR 21686).
-    BIP350: Anwani za matokeo asili ya shahidi v1+ hutumia bech32m badala ya bech32 kuanzia v22.0 (PR 20861).
-    BIP371: Sehemu za Taproot kwa PSBT kuanzia v24.0 (PR 22558).
-    BIP380 381 382 383 384 385: Vielelezo vya Hati ya Tokeo, na sehemu nyingi za Maneno ya Hati zimetekelezwa kuanzia v0.17.0 (PR 13697).
-    BIP386: Vielelezo vya Hati ya Tokeo vya +tr()+ vimetekelezwa((("BIPs (Bitcoin Improvement Proposals)", "implemented by Bitcoin Core", startref="bips-implement")))((("Bitcoin Core", "BIPs implemented by", startref="bitcoin-core-bips"))) kuanzia v22.0 (PR 22051).
