[[ch11]]
== Usalama wa Bitcoin

Kulinda bitcoini zako ni changamoto kwa sababu bitcoini
si kama salio kwenye akaunti ya benki. Bitcoini zako zinafanana sana na pesa taslimu za kidijitali au dhahabu. Labda umesikia msemo, «Umiliki ni sehemu tisa kumi za sheria». Kweli, katika Bitcoin, umiliki ni sehemu kumi kumi za sheria. Umiliki wa funguo za kutumia bitcoini fulani ni sawa na umiliki wa pesa taslimu au kipande cha chuma cha thamani. Unaweza kuzipoteza, kuziweka mahali pasipofaa, kuziibiwa, au kwa bahati mbaya kumpa mtu kiasi kibaya. Katika kila moja ya hali hizi, watumiaji hawana njia ya kujirekebisha ndani ya itifaki, kana kwamba wameangusha pesa kwenye barabara ya umma.

Hata hivyo, mfumo wa Bitcoin una uwezo ambao pesa taslimu, dhahabu, na akaunti za benki hazina. Pochi ya Bitcoin, yenye funguo zako, inaweza kuakibishwa kama faili lolote. Inaweza kuhifadhiwa katika nakala nyingi, hata kuchapishwa kwenye karatasi kwa nakala ngumu ya akiba. Huwezi «kuakibishwa» pesa taslimu, dhahabu, au akaunti za benki. Bitcoin ni tofauti kiasi kikubwa na kitu chochote kilichokuja kabla kwamba tunahitaji kufikiria pia jinsi ya kulinda bitcoini zetu kwa njia mpya.

=== Kanuni za Usalama

Kanuni ((("Bitcoin", "security", "principles of", id="bitcoin-security-principle")))((("security", "principles of", id="security-principle")))((("decentralized consensus", "as security principle", secondary-sortas="security principle", id="decentral-consensus-principle")))kuu katika Bitcoin ni ugawanyaji na ina athari muhimu kwa usalama. Mfano wa sentralizesheni, kama benki ya kawaida au mtandao wa malipo, unategemea udhibiti wa ufikiaji na uhakiki ili kuwazuia wahalifu wasio na nia njema nje ya mfumo. Kwa kulinganisha, mfumo wa desentralizesheni kama Bitcoin unapeleka wajibu na udhibiti kwa watumiaji. Kwa sababu usalama wa mtandao unategemea uthibitisho wa kujitegemea, mtandao unaweza kuwa wazi na hakuna usimbuaji unaohitajika kwa trafiki ya Bitcoin (ingawa usimbuaji bado unaweza kuwa wa manufaa).

Kwenye mtandao wa malipo wa kawaida, kama mfumo wa kadi ya mkopo, malipo ni ya wazi kwa sababu yanajumuisha kitambulisho cha kibinafsi cha mtumiaji (nambari ya kadi ya mkopo). Baada ya malipo ya awali, mtu yeyote mwenye ufikiaji wa kitambulisho anaweza «kuvuta» fedha na kuweza mtumiaji tena na tena. Hivyo, mtandao wa malipo lazima ufungwe kutoka mwisho hadi mwisho kwa usimbuaji na lazima uhakikishe kwamba wasikiaji haramu wala wasuluhishi wa kati hawawezi kuhatarisha trafiki ya malipo wakati wa usafirishaji au inapohifadhiwa (wakati wa kupumzika). Ikiwa mhalifu anapata ufikiaji wa mfumo, anaweza kuhatarisha miamala ya sasa _na_ tokeni za malipo ambazo zinaweza kutumika kuunda miamala mpya. Vibaya zaidi, data ya wateja inapohatariwa, wateja wanakabiliwa na wizi wa utambulisho na lazima wachukue hatua kuzuia matumizi ya udanganyifu ya akaunti zilizohatariwa.

Bitcoin ni tofauti kabisa. Muamala wa Bitcoin unaidhinisha thamani maalum tu kwa mpokeaji maalum na hauwezi kuigwa. Haufichi habari yoyote ya kibinafsi, kama vile utambulisho wa wahusika, na hauwezi kutumika kuidhinisha malipo ya ziada. Kwa hivyo, mtandao wa malipo wa Bitcoin hauhitaji kusimbwa au kulindwa dhidi ya usikilizaji haramu. Kwa kweli, unaweza kusambaza miamala ya Bitcoin kwenye njia ya wazi ya umma, kama WiFi isiyolindwa au Bluetooth, bila kupoteza usalama.

Mfano wa usalama wa desentralizesheni wa Bitcoin unaweka nguvu nyingi mikononi mwa watumiaji. Pamoja na nguvu hiyo kuja wajibu wa kudumisha usiri wa funguo zao. Kwa watumiaji wengi hilo si rahisi kufanya, hasa kwenye vifaa vya kompyuta vya matumizi ya jumla kama simu mahiri zilizounganika na mtandao au kompyuta ndogo. Ingawa mfano wa desentralizesheni wa Bitcoin unazuia aina ya kuhatariwa kwa wingi kunaoonekana na kadi za mkopo, watumiaji wengi hawafanikii kulinda funguo zao kwa kutosha na wanaibiwa, mmoja mmoja.

==== Kutengeneza Mifumo ya Bitcoin kwa Usalama

Kanuni muhimu
kwa wasanidi programu wa Bitcoin ni ugawanyaji. Wasanidi programu wengi watajua mifano ya usalama ya sentralizesheni na wanaweza kushawishika kuomba mifano hii kwa programu zao za Bitcoin, kwa matokeo mabaya.

Usalama wa Bitcoin unategemea udhibiti wa desentralizesheni juu ya funguo na uthibitisho wa kujitegemea wa miamala na watumiaji. Ukitaka kuchukua faida ya usalama wa Bitcoin, unahitaji kuhakikisha unabaki ndani ya mfano wa usalama wa Bitcoin. Kwa maneno rahisi: usichukue udhibiti wa funguo kutoka kwa watumiaji na usitoe uthibitisho nje.

Kwa mfano, masoko mengi ya mapema ya Bitcoin yalikusanya fedha zote za watumiaji katika pochi moja «moto» yenye funguo zilizohifadhiwa kwenye seva moja. Muundo kama huo unaondoa udhibiti kutoka kwa watumiaji na unaentralizesha udhibiti juu ya funguo kwenye mfumo mmoja. Mifumo mingi kama hiyo imevunjwa, kwa matokeo mabaya kwa wateja wao.

Isipokuwa uko tayari kuwekeza sana katika usalama wa uendeshaji, safu nyingi za udhibiti wa ufikiaji, na ukaguzi (kama benki za kawaida zinavyofanya), unapaswa kufikiria kwa makini sana kabla ya kuchukua fedha nje ya muktadha wa usalama wa desentralizesheni wa Bitcoin. Hata kama una fedha na nidhamu ya kutekeleza mfano thabiti wa usalama, muundo kama huo tu unakurudia mfano dhaifu wa mitandao ya fedha ya kawaida, ulioathiriwa na wizi wa utambulisho, ufisadi, na ubadhirifu. Kuchukua faida ya mfano wa kipekee wa usalama wa desentralizesheni wa Bitcoin, lazima uepuke jaribu la usanifu wa sentralizesheni ambao unaweza kuonekana unaojulikana lakini hatimaye unaathiri usalama wa ((("decentralized consensus", "as security principle", secondary-sortas="security principle", startref="decentral-consensus-principle")))Bitcoin.

==== Mzizi wa Uaminifu

Usanifu ((("root of trust", id="root-trust")))wa usalama wa kawaida unategemea dhana inayoitwa _mzizi wa uaminifu_, ambayo ni msingi wa kuaminika unaotumika kama msingi wa usalama wa mfumo au programu kwa ujumla. Usanifu wa usalama unaendelezwa kuzunguka mzizi wa uaminifu kama mfululizo wa miduara ya mkusanyiko, kama safu kwenye vitunguu saumu, ukipanua uaminifu nje kutoka katikati. Kila safu inajengwa juu ya safu ya ndani inayoaminika zaidi kwa kutumia udhibiti wa ufikiaji, saini za kidijitali, usimbuaji, na primitifu zingine za usalama. Mifumo ya programu inavyokuwa ngumu zaidi, ina uwezekano mkubwa zaidi wa kuwa na hitilafu, ambazo huwafanya kuwa hatarini kwa kuhatariwa kwa usalama. Kwa sababu hiyo, mfumo wa programu unavyokuwa ngumu zaidi, ndivyo unavyokuwa vigumu kulinda. Dhana ya mzizi wa uaminifu inahakikisha kwamba uaminifu mkubwa zaidi unawekwa ndani ya sehemu ndogo ya ugumu wa mfumo, na kwa hivyo sehemu ndogo zaidi za hatari za mfumo, huku programu ngumu zaidi ikiwekwa kuzunguka hiyo. Usanifu huu wa usalama unarudiwa kwa viwango tofauti, kwanza ukianzisha mzizi wa uaminifu ndani ya vifaa vya mfumo mmoja, kisha ukipanua mzizi wa uaminifu huo kupitia mfumo wa uendeshaji hadi huduma za mfumo wa kiwango cha juu, na hatimaye kwa seva nyingi zilizowekwa katika miduara ya mkusanyiko ya uaminifu unaopungua.

Usanifu wa usalama
wa Bitcoin ni tofauti. Katika Bitcoin, mfumo wa makubaliano unaunda mnyororo wa vitalu unaoaminika ambao umegawanywa kabisa. Mnyororo wa vitalu uliothibitishwa kwa usahihi unatumia kitalu cha asili kama mzizi wa uaminifu, ukiunda mnyororo wa uaminifu hadi kitalu cha sasa. Mifumo ya Bitcoin inaweza na inapaswa kutumia mnyororo wa vitalu kama mzizi wao wa uaminifu. Ukitengeneza programu ngumu ya Bitcoin inayojumuisha huduma kwenye mifumo mingi tofauti, unapaswa kuchunguza kwa makini usanifu wa usalama ili kujua ambapo uaminifu unawekwa. Hatimaye, kitu pekee kinachopaswa kuaminiwa kwa uwazi ni mnyororo wa vitalu uliothibitishwa kabisa. Ikiwa programu yako kwa uwazi au kwa kufichwa inaweka uaminifu katika kitu chochote isipokuwa mnyororo wa vitalu, hiyo inapaswa kuwa chanzo cha wasiwasi kwa sababu inaanzisha udhaifu. Njia nzuri ya kutathmini usanifu wa usalama wa programu yako ni kuzingatia kila sehemu ya mtu binafsi na kutathmini hali ya nadharia ambapo sehemu hiyo inahatariwa kabisa na iko chini ya udhibiti wa mhalifu. Chukua kila sehemu ya programu yako, kwa zamu, na tathmini athari kwenye usalama wa jumla ikiwa sehemu hiyo inahatariwa. Ikiwa programu yako haiko salama tena wakati sehemu zinahatariwa, hiyo inaonyesha umeweka uaminifu vibaya katika sehemu hizo. Programu ya Bitcoin isiyo na udhaifu inapaswa kuwa hatarini tu kwa kuhatariwa kwa mfumo wa makubaliano wa Bitcoin, ikimaanisha kwamba mzizi wake wa uaminifu unategemea sehemu yenye nguvu zaidi ya usanifu wa usalama wa Bitcoin.

Mifano mingi ya masoko ya Bitcoin yaliyovunjwa inasaidia kukuza nukta hii kwa sababu usanifu na muundo wao wa usalama unashindwa hata chini ya uchunguzi wa kawaida zaidi. Utekelezaji huu wa sentralizesheni ulikuwa umeweka uaminifu kwa uwazi katika vipengele vingi nje ya mnyororo wa vitalu wa Bitcoin, kama vile pochi moto, hifadhidata za sentralizesheni, funguo za usimbuaji zenye udhaifu, na ((("Bitcoin", "security", "principles of", startref="bitcoin-security-principle")))((("security", "principles of", startref="security-principle")))((("root of trust", startref="root-trust")))mipango inayofanana.

=== Mazoea Bora ya Usalama wa Mtumiaji

Binadamu ((("Bitcoin", "security", "best practices", id="bitcoin-security-best-practice")))((("security", "best practices", id="security-best-practice")))((("best practices, security", id="best-practice-security")))wametumia udhibiti wa usalama wa kimwili kwa maelfu ya miaka. Kwa kulinganisha, uzoefu wetu na usalama wa kidijitali ni chini ya miaka 50. Mifumo ya uendeshaji ya kisasa ya matumizi ya jumla si salama sana na haifai haswa kwa kuhifadhi pesa za kidijitali. Kompyuta zetu zinakabiliwa mara kwa mara na vitisho vya nje kupitia miunganiko ya mtandao ya saa zote. Zinaendesha maelfu ya vipande vya programu kutoka kwa waandishi mamia, mara nyingi na ufikiaji usio na kikomo kwa faili za mtumiaji. Kipande kimoja cha programu ovu, kati ya maelfu mengi yaliyowekwa kwenye kompyuta yako, kinaweza kuhatarisha kibodi na faili zako, ukiiba bitcoini yoyote iliyohifadhiwa katika programu za pochi. Kiwango cha matengenezo ya kompyuta kinachohitajika ili kuweka kompyuta bila virusi na bila trojan kiko nje ya kiwango cha ujuzi wa wote ila kwa asilimia ndogo ya watumiaji wa kompyuta.

Licha ya miongo ya utafiti na maendeleo katika usalama wa habari, mali za kidijitali bado zinaathiriwa sana na mpinzani aliyejitolea. Hata mifumo iliyo salama zaidi na iliyozuiwa zaidi, katika kampuni za huduma za fedha, mashirika ya ujasusi, na wakandarasi wa ulinzi, mara nyingi huvunjwa. Bitcoin inaunda mali za kidijitali zenye thamani ya asili na zinaweza kuibiwa na kupelekwa kwa wamiliki wapya mara moja na kwa kudumu. Hii inaunda kivutio kikubwa kwa wavamizi. Hadi sasa, wavamizi walilazimika kubadilisha habari za utambulisho au tokeni za akaunti—kama vile kadi za mkopo na akaunti za benki—kuwa thamani baada ya kuzivunja. Licha ya ugumu wa kuuza na kusafisha habari za fedha, tumeona wizi unaozidi zaidi. Bitcoin inazidisha tatizo hili kwa sababu haihitaji kuuzwa au kusafishwa; bitcoini zina thamani zenyewe.

Bitcoin pia inaunda vivutio vya kuboresha usalama wa kompyuta. Ingawa awali hatari ya kuhatariwa kwa kompyuta ilikuwa ya udhaifu na isiyo ya moja kwa moja, Bitcoin inafanya hatari hizi kuwa wazi na dhahiri. Kubeba bitcoini kwenye kompyuta kunasaidia kuelekeza akili ya mtumiaji kwenye haja ya kuboresha usalama wa kompyuta. Kama matokeo ya moja kwa moja ya kuenea na kupitishwa zaidi kwa Bitcoin na sarafu zingine za kidijitali, tumeona ongezeko la mbinu za uvamizi na suluhisho za usalama. Kwa maneno rahisi, wavamizi sasa wana lengo zuri sana na watumiaji wana kivutio wazi cha kujilinda.

Katika miaka mitatu iliyopita, kama matokeo ya moja kwa moja ya kupitishwa kwa Bitcoin, tumeona uvumbuzi mkubwa katika uwanja wa usalama wa habari kwa namna ya usimbuaji wa vifaa, hifadhi ya funguo na vifaa vya saini vya vifaa, teknolojia ya multisaini, na escrow ya kidijitali. Katika sehemu zifuatazo tutachunguza mazoea mbalimbali bora ya usalama wa vitendo wa mtumiaji.

==== Kuhifadhi Bitcoini kwa Njia ya Kimwili

Kwa sababu watumiaji wengi ((("bitcoins", "physical storage")))((("physical bitcoin storage")))((("storing bitcoins", id="storing-bitcoin")))wana ustarehe zaidi na usalama wa kimwili kuliko usalama wa habari, njia bora sana ya kulinda bitcoini ni kubadilisha kuwa fomu ya kimwili. Funguo za Bitcoin, na mbegu zinazotumiwa kuziunda, si chochote zaidi ya nambari ndefu. Hii inamaanisha kwamba zinaweza kuhifadhiwa katika fomu ya kimwili, kama vile kuchapishwa kwenye karatasi au kukatwa kwenye sahani ya chuma. Kulinda funguo kisha inakuwa rahisi kama kulinda kimwili nakala iliyochapishwa ya mbegu ya funguo. Mbegu inayochapishwa kwenye karatasi inaitwa «akiba ya karatasi», na pochi nyingi zinaweza kuziunda. Kubeba bitcoini
nje ya mtandao inaitwa ((("cold storage")))_hifadhi baridi_ na ni moja ya mbinu bora zaidi za usalama. Mfumo wa hifadhi baridi ni ule ambapo funguo zinazalishwa kwenye mfumo wa nje ya mtandao (ule ambao haujawahi kuunganika kwenye mtandao) na kuhifadhiwa nje ya mtandao kwenye karatasi au kwenye vifaa vya kidijitali, kama kidude cha kumbukumbu cha USB.

==== Vifaa vya Saini vya Vifaa

Kwa muda ((("hardware signing devices")))mrefu, usalama wa Bitcoin unaweza kuzidi kuchukua fomu ya vifaa vya saini vya vifaa visivyoweza kubadilishwa. Tofauti na simu mahiri au kompyuta ya mezani, kifaa cha saini cha vifaa cha Bitcoin kinahitaji tu kubeba funguo na kuzitumia kuzalisha saini. Bila programu ya matumizi ya jumla ya kuhatarisha na kwa miingiliano midogo, vifaa vya saini vya vifaa vinaweza kutoa usalama imara kwa watumiaji wasio wataalamu. Vifaa vya saini vya vifaa vinaweza kuwa njia kuu ya kuhifadhi bitcoini.

==== Kuhakikisha Ufikiaji Wako

Ingawa
watumiaji wengi ((("backing up", "importance of")))kwa haki wana wasiwasi kuhusu wizi wa bitcoini zao, kuna hatari kubwa zaidi. Faili za data zinapotea kila wakati. Zikijumuisha funguo za Bitcoin, upotevu ni chungu zaidi. Katika juhudi za kulinda pochi zao za Bitcoin, watumiaji lazima wawe makini sana wasizidi mbali na hatimaye kupoteza bitcoini zao. Mnamo Julai 2011, mradi maarufu wa uhamasishaji na elimu wa Bitcoin ulipoteza karibu bitcoini 7,000. Katika juhudi zao za kuzuia wizi, wamiliki walikuwa wametekeleza mfululizo mgumu wa akiba zilizosimbwa. Hatimaye walipoteza kwa bahati mbaya funguo za usimbuaji, na kufanya akiba kuwa zisizo na thamani na kupoteza utajiri. Kama kuficha pesa kwa kuizika jangwani, ukilinda bitcoini zako vizuri sana unaweza kushindwa kuzipata tena.

[WARNING]
====
Ili kutumia bitcoini, unaweza((("wallets", "recovery codes")))((("recovery codes"))) kuhitaji kuakibishwa zaidi ya funguo zako za kibinafsi au mbegu ya BIP32 inayotumiwa kuzipata. Hii ni hali hasa wakati multisaini au hati ngumu zinatumika. Hati nyingi za matokeo zinafunga kwa masharti halisi ambayo lazima yakidhiwe kutumia bitcoini katika matokeo hayo, na haiwezekani kutimiza ahadi hiyo isipokuwa programu yako ya pochi inaweza kufunua masharti hayo kwa mtandao. Misimbo ya uokoaji wa pochi lazima ijumuishe habari hii. Kwa maelezo zaidi, ona <<ch05_wallets>>.
====

==== Kutofautisha Hatari

Je, ((("risk diversification")))((("storing bitcoins", startref="storing-bitcoin")))ungebeba thamani yako yote ya wavu kwa pesa taslimu kwenye pochi yako? Watu wengi wangeona hilo kama upuuzi, lakini watumiaji wa Bitcoin mara nyingi hubeba bitcoini zao zote kwa kutumia programu moja ya pochi. Badala yake, watumiaji wanapaswa kutawanya hatari kati ya programu nyingi na tofauti za Bitcoin. Watumiaji waangalifu wataweka sehemu ndogo tu, labda chini ya 5%, ya bitcoini zao katika pochi ya mtandaoni au ya simu kama «chenji ya mfukoni». Iliyobaki inapaswa kugawanywa kati ya mifumo michache tofauti ya hifadhi, kama pochi ya kompyuta ya mezani na ya nje ya mtandao (hifadhi baridi).

==== Multisaini na Utawala

Wakati wowote kampuni ((("multisignature addresses")))((("addresses", "multisignature")))au mtu binafsi anapohifadhi kiasi kikubwa cha bitcoini, wanapaswa kuzingatia kutumia anwani ya Bitcoin ya multisaini. Anwani za multisaini zinalinda fedha kwa kuhitaji saini zaidi ya moja kufanya malipo. Funguo za saini zinapaswa kuhifadhiwa katika maeneo kadhaa tofauti na chini ya udhibiti wa watu tofauti. Katika mazingira ya shirika, kwa mfano, funguo zinapaswa kuzalishwa kwa kujitegemea na kushikwa na watendaji kadhaa wa kampuni ili kuhakikisha kwamba hakuna mtu mmoja anayeweza kuhatarisha fedha. Anwani za multisaini pia zinaweza kutoa upungufu, ambapo mtu mmoja anashikilia funguo kadhaa zilizohifadhiwa katika maeneo tofauti.


==== Uwezo wa Kuendelea Kuishi

Hali muhimu moja
ya usalama ((("survivability (of bitcoin access)")))((("estate planning")))ambayo mara nyingi hupuuzwa ni upatikanaji, hasa katika muktadha wa ulemavu au kifo cha mmiliki wa funguo. Watumiaji wa Bitcoin wanaambiwa kutumia manenosiri magumu na kuweka funguo zao salama na za kibinafsi, zisishirikiwe na mtu yeyote. Kwa bahati mbaya, mazoea hayo yanafanya karibu kuwa haiwezekani kwa familia ya mtumiaji kurudisha fedha yoyote ikiwa mtumiaji hapafikiki kuzifungua. Katika hali nyingi, kwa kweli, familia za watumiaji wa Bitcoin zinaweza kuwa hazijui kabisa kuhusu uwepo wa fedha za bitcoin.

Ukiwa na bitcoini nyingi, unapaswa kuzingatia kushiriki maelezo ya ufikiaji na ndugu anayeaminika au wakili. Mpango ngumu zaidi wa uwezo wa kuendelea kuishi unaweza kuanzishwa na ufikiaji wa multisaini na kupanga mali kupitia wakili aliyebobea kama «msimamizi wa mali za kidijitali».

Bitcoin ni teknolojia mpya ngumu ambayo bado inachunguzwa na wasanidi programu. Kwa muda tutaendeleza zana bora za usalama na mazoea ambayo ni rahisi zaidi kutumia na wasio wataalamu. Kwa sasa, watumiaji wa Bitcoin wanaweza kutumia vidokezo vingi vilivyojadiliwa hapa kufurahia uzoefu wa Bitcoin salama na ((("Bitcoin", "security", "best practices", startref="bitcoin-security-best-practice")))((("security", "best practices", startref="security-best-practice")))((("best practices, security", startref="best-practice-security")))usio na matatizo.
